### ISSUE TITLE
error bug

### ISSUE THREAD

**Issue by wkox** [ugurozturk/instabot.pyV2#12]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [ yes] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ) 
- [y ] Searched and checked orher issues about my problem 
- [y ] I have errors.log file and i did upload it

Check One :
- [y ] Bug
- [ ] Feature
- [ ] Need Help

### VPS: Is the vps far far away ? Another Country ?no
- [x] VPS: Tried the same code via my local pc

## What is your python knowledge vote 0/10
-1
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2\src\instabot.py", line 688, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2\src\instabot.py", line 749, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2\src\instabot.py", line 806, in auto_unfollow
    current_id = username_row[0]
TypeError: 'bool' object is not subscriptable

**Comment by ugurozturk** [comment]
@wkox the thing is, i re-cloned and tried to run code and yeah everything looks working. But i figured something. So update your repo or remove then re clone it.

**Comment by bloggerpact** [comment]
@ugurozturk hey i m also getting a error

$ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "G:\www\Instabot\instabot.pyV2\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "G:\www\Instabot\instabot.pyV2\src\instabot.py", line 696
    min=self.start_at_m), end="\r")
                             ^
SyntaxError: invalid syntax

**Comment by ugurozturk** [comment]
@bloggerpact please open new issue.

**Comment by ugurozturk** [comment]
@wkox i think i fixed it. If you have any problem, open new issue or ask for this one to be re-open.
