### ISSUE TITLE
Failed after 12 hours / commenting turned on

### ISSUE THREAD

**Issue by davidwaite** [ugurozturk/instabot.pyV2#22]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [X ] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [X] Searched and checked other issues about my problem
- [X ] If have errors.log file and i did upload it

Check One :
- [X] Bug
- [ ] Feature
- [X] Need Help

## What OS ?
Linux mint 18 Cinnamon 3.0.7
## Python Version ?
2.7
## Is it VPS ?
No
### VPS: Is the vps far far away ? Another Country ?
n/a
- [ ] VPS: Tried the same code via my local pc
n/a
## What is your python knowledge vote 0/10
4

Issue
after running 12 hours it failed and logged out. i do have commenting on at "300"

heres the error stack from terminal and ive attached error log
[errors.log](https://github.com/ugurozturk/instabot.pyV2/files/1605633/errors.log)

04.01.2018_20:31 Removing already liked medias..
```
Traceback (most recent call last):
  File "example.py", line 75, in <module>
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
  File "/home/david/Desktop/instabot.pyV2-masterv2/src/instabot.py", line 691, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/david/Desktop/instabot.pyV2-masterv2/src/instabot.py", line 759, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/home/david/Desktop/instabot.pyV2-masterv2/src/instabot.py", line 783, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
04.01.2018_20:32 Logout: likes - 659, follow - 0, unfollow - 0, comments - 293.
04.01.2018_20:32 Bot work time: 23:47:01.345714
04.01.2018_20:32 Logout success!
```

**Comment by Victorrussia** [comment]
The same thing. It happens on my accounts usually near 100 likes + follows

**Comment by ugurozturk** [comment]
@Victorrussia which python version are you using ?

**Comment by ugurozturk** [comment]
@davidwaite @Victorrussia @eastcoastboys i dont using commenting feature and the error shows up after a while so i can't debug / find the error myself. So i need you guys help. I made a new branch to track this error.First remove error.log then use this branch. https://github.com/ugurozturk/instabot.pyV2/tree/check_exisiting_comment_fix  The program wouldn't stop anymore but be awere it will always fail like that in the back. To make it run smooth and fix this, after a while check the error.log and if there is a input "check_exisiting_comment" then send the file here.

**Comment by Victorrussia** [comment]
@ugurozturk I am using 2.7 python and I use website pythonanywhere.com to host this bot and run it there. I will reload this now and write you if find "check_exisiting_comment" inside error.log

**Comment by Victorrussia** [comment]
@ugurozturk I have just tried to run instabot.py in my console and found this mistake. I am not sure if it helps but I have informed you about this.
```
Traceback (most recent call last):
  File "/home/victorananyev/новая турок исправил/src/instabot.py", line 5, in <module>
    from .unfollow_protocol import unfollow_protocol
ValueError: Attempted relative import in non-package
>>> 
```

**Comment by ugurozturk** [comment]
@Victorrussia is it fails always like that ? it can't be o.o

**Comment by Victorrussia** [comment]
Now happened this in example.py. Up I sent to you instabot.py which I just ran for test.
![image](https://user-images.githubusercontent.com/33234413/34612018-fce5502c-f238-11e7-9e1f-e7621e3ee0d2.png)

**Comment by Victorrussia** [comment]
@ugurozturk  Here is my logs in error.txt. There are a lot of "check_exisiting_comment"
[error.txt](https://github.com/ugurozturk/instabot.pyV2/files/1606766/error.txt)

**Comment by ugurozturk** [comment]
@Victorrussia i think the server side has some problem. 
```
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (31): i.instagram.com
```
Check the requests module version by pip freeze . And please use python 3 then lets see what the real problem is. Also i updated the code on the branch. About TypeError. Probabby this is also happening when you getting the status_code different than 200 and 400. 

So keep in touch to fix this.

**Comment by Victorrussia** [comment]
@ugurozturk I have just checked status_code in instabot.py and all values are 200 or 400 so I haven't changed it by myself. Also I updated instabot.py which you have changed one hour ago. Probably I have to use newer python. I will write soon about my successes:) Thanks a lot for fast answers

**Comment by raffg** [comment]
@ugurozturk I've just received this same error myself. I'm using my own fork of the original project, and just updated it with your fixes for the "except on get_media" bug from a few days ago. I'm using python 2.7 on Ubuntu.

`
Traceback (most recent call last):
  File "xxxx.py", line 86, in <module>
    bot.new_auto_mod()
  File "/home/xxxx/xxxx/src/instabot.py", line 596, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/xxxx/xxxx/src/instabot.py", line 669, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/home/xxxx/xxxx/src/instabot.py", line 693, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/home/xxxx/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/xxxx/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/xxxx/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by Victorrussia** [comment]
@ugurozturk I switched my example.py 2.7 in 3.5 version by deleting 2 first lanes in file: #!/usr/bin/env python
It wrote me that it is python 3.5 console now but I am not sure if it has switched everything in common on 3.5. So I waited some time and got this mistake. 
I suppose the problem is in switching between 2.7 and 3.5. If you could do this I think this mistake will be deleted.
# -*- coding: utf-8 -*-
![image](https://user-images.githubusercontent.com/33234413/34623230-69f0f770-f261-11e7-9ca5-4b09236a1d02.png)

**Comment by davidwaite** [comment]
@ugurozturk first thanks for your responses and all your help!... so ive upgraded my python from 2.7 to 3.6.3 and am now running your new branch "check_exisiting_comment_fix" 
- i run with no follow or unfollow
- commenting enabled at 200
- i run this on my own computer no external server

Its been running for about an hour no errors yet... if it fails ill send you the terminal stack and error.log
thanks

**Comment by ugurozturk** [comment]
@Victorrussia If i am not wrong they are just comment lines. Nothing gonna happen by removing them or adding them in the runtime. You probabby need to run like `python3 example.py` I dont know the detail about pythonanywhere . com

**Comment by ugurozturk** [comment]
@davidwaite i am running about 2days now without any error at my android device.

**Comment by raffg** [comment]
@ugurozturk In both python 2.7 and python 3.6, I'm getting this `ValueError: No JSON object could be decoded` error. Commenting is on.

**Comment by ugurozturk** [comment]
@raffg i need some details. Can you write here do you using pythonanywhere ? or local machine ? Also can you write your requests module version ? it can be shown by `pip freeze `

**Comment by raffg** [comment]
@ugurozturk I'm using my local machine, Ubuntu 16.04; requests==2.13.0. Thanks for all your work, by the way!

**Comment by ugurozturk** [comment]
@raffg can you upgrade the requests to latest one ? it is http://docs.python-requests.org/en/master/ 
`pip install requests --upgrade` also i did update the check_exisiting_comment_fix branch which logs the media_code to tracking purpose. So i can check the medias to why they doesn't works to. Please use https://github.com/ugurozturk/instabot.pyV2/tree/check_exisiting_comment_fix and check the error.log sometimes. if there a input "check_exisiting_comment" send the error.log here

**Comment by raffg** [comment]
@ugurozturk I updated requests and it ran for two hours with no issues. I'll let you know if the error reoccurs. Thanks!

**Comment by ugurozturk** [comment]
@davidwaite is this latest one of the branch "check_exisiting_comment_fix" im asking because there is not logged any media_code.

**Comment by ugurozturk** [comment]
@raffg as i said, the script would not be stopped as like before. Please check the error.log file for the error detail

**Comment by davidwaite** [comment]
@davidwaite ok so i updated and am using the current branch (been running for a few hours)
here is the error log. let me know what you think
thanks for everything!
[errors.log](https://github.com/ugurozturk/instabot.pyV2/files/1609383/errors.log)

**Comment by ugurozturk** [comment]
@davidwaite i found something and did change the code. And deleted try / catch to make the code better performance. Yet, the bot might stop again like before or will better work. I can't test it by myself because i dont use the commenting feature. So please test it for help the repo.

**Comment by davidwaite** [comment]
will do... i'll do it right now thanks!

**Comment by ugurozturk** [comment]
@davidwaite any news ?? is the code stopped or it is running as well as should be ?

**Comment by davidwaite** [comment]
@ugurozturk its still running!.. looks like there hasnt been any errors. here is the error log which has the debugging. there were some 400 though in it. let me know if this looks functional to you.
[errors.log](https://github.com/ugurozturk/instabot.pyV2/files/1610110/errors.log)

**Comment by ugurozturk** [comment]
@davidwaite Yeah it does working nice. Still you should upgrade your requests module then your python will run better than ever. `pip install requests --upgrade`

**Comment by davidwaite** [comment]
@ugurozturk Sweet! k will do... let you know if any thing errors
thanks for all your help!

**Comment by davidwaite** [comment]
@ugurozturk since the error.log with continue to increase in size... do you have built in a way to shut that portion off or point me to where i can comment out the lines?

**Comment by ugurozturk** [comment]
@davidwaite the thing is means you are having troubles via requests module. Also notice that `The use of Python 3 is highly preferred over Python 2` from requests module [doc](http://docs.python-requests.org/en/master/).

Anyway the answer is in the instabot.py line 99 `logging.basicConfig(filename='errors.log', level=logging.DEBUG)` if you delete this line it wouldn't debug and log to file

**Comment by davidwaite** [comment]
@ugurozturk clarify for me.. i sent you my error log last time and you said its working nice. ive since upgraded my requests module "pip install requests --upgrade"... and im running this on python 3.6.3... this should be working correct??  here is the error log after i updated the request... does it look good?
[errors.log](https://github.com/ugurozturk/instabot.pyV2/files/1613693/errors.log)

**Comment by ugurozturk** [comment]
as much as i know there is 3 things. One of them just shows success (200 status code) posts. The other thing sometimes instagram connection drops, it is nothing to do via the repo. The other thing it is weirdly failing in like_all_exist_media when there is not comment on it. Yet there have to, because we are finding them via the tags in comment[0] . Still i also did some changes for it. update your code via last commit of masterv2 branch

**Comment by davidwaite** [comment]
ok ill update with the latest, and monitor
thanks!
