### ISSUE TITLE
Please, I need help! 

### ISSUE THREAD

**Issue by raw001** [ugurozturk/instabot.pyV2#28]
Hi, 

I don't know how to fix this problem. I attached below the code: 

Traceback (most recent call last):
  File "C:\Users\raulm\Desktop\Bot\example - copia (5).py", line 82, in <module>
    bot.new_auto_mod()
  File "C:\Users\raulm\Desktop\Bot\src\instabot.py", line 684, in new_auto_mod
    self.new_auto_mod_like()
  File "C:\Users\raulm\Desktop\Bot\src\instabot.py", line 712, in new_auto_mod_like
    if self.like_all_exist_media(media_size=1, delay=False):
  File "C:\Users\raulm\Desktop\Bot\src\instabot.py", line 461, in like_all_exist_media
    if check_already_liked(self, media_id=self.media_by_tag[i]['node']['id']) == 1:
  File "C:\Users\raulm\Desktop\Bot\src\sql_updates.py", line 43, in check_already_liked
    media_id + "' LIMIT 1)").fetchone()[0] > 0:
sqlite3.OperationalError: database is locked
>>> 

Thank you in advance!

R

**Comment by ugurozturk** [comment]
@raw001 Even i do really wondering the problem's details but.. there is rules. When you create new issue do read the issue_template and fill it. https://github.com/ugurozturk/instabot.pyV2/blob/masterv2/ISSUE_TEMPLATE.md other wise the number one rule is "Fill all requirements before sending issues. Or all issues will be closed without reading."
