### ISSUE TITLE
Repeated Follows

### ISSUE THREAD

**Issue by iceman183** [ugurozturk/instabot.pyV2#36]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [x] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ) 
- [x] Searched and checked other issues about my problem
- [x] If have errors.log file and i did upload it - Was rewritten by a new run so no sorry

Check One :
- [x] Bug  - Yes

## What OS ?
Centos 6.9
## Python Version ?
3.3
## Is it VPS ?
Yes
### VPS: Is the vps far far away ? Another Country ?
Yes
- [x] VPS: Tried the same code via my local pc
?
## What is your python knowledge vote 4/10

````
2018-01-10 22:30:28,770 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:29,613 - someusername - Followed: 6698255828 #4.
2018-01-10 22:30:32,996 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:33,570 - someusername - Followed: 6698255828 #5.
2018-01-10 22:30:36,962 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:37,434 - someusername - Followed: 6698255828 #6.
2018-01-10 22:30:40,813 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:41,283 - someusername - Followed: 6698255828 #7.
2018-01-10 22:30:44,671 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:45,116 - someusername - Followed: 6698255828 #8.
2018-01-10 22:30:48,493 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:48,964 - someusername - Followed: 6698255828 #9.
2018-01-10 22:30:52,368 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:52,800 - someusername - Followed: 6698255828 #10.
2018-01-10 22:30:56,186 - someusername - Trying to follow: 6698255828
2018-01-10 22:30:56,630 - someusername - Followed: 6698255828 #11.

````

Checked my logs and saw this. You encountered this before or know why it kept following the same person and adding to the counter?

Also why does it remove already liked medias everytime it gets a new tag? 

````
2018-01-10 22:35:35,813 - someusername - Get media id by tag: landscapephotography
2018-01-10 22:35:37,950 - someusername - Removing already liked medias..
2018-01-10 22:35:37,954 - someusername - Trying to follow: 6264353076
2018-01-10 22:35:38,654 - someusername - Followed: 6264353076 #1.
2018-01-10 22:35:39,864 - someusername - Trying to comment: 1689330599166501837
2018-01-10 22:35:41,030 - someusername - Write: "Nice shot! :)". #1.
2018-01-10 22:37:47,535 - someusername - Trying to like media: 1689330599166501837
2018-01-10 22:37:48,416 - someusername - Liked: 1689330599166501837. Like #2.
2018-01-10 22:37:52,013 - someusername - Get media id by tag: landscapephotography
2018-01-10 22:37:54,329 - someusername - Removing already liked medias..
2018-01-10 22:39:54,465 - someusername - Trying to like media: 1689331780928587520
2018-01-10 22:39:55,097 - someusername - Liked: 1689331780928587520. Like #3.
2018-01-10 22:42:07,830 - someusername - Trying to like media: 1689331763439961436
2018-01-10 22:42:08,669 - someusername - Liked: 1689331763439961436. Like #4.
2018-01-10 22:42:46,525 - someusername - Trying to comment: 1689331762959828944
2018-01-10 22:42:47,462 - someusername - Write: "Amazing shot!". #2.
2018-01-10 22:43:14,866 - someusername - Trying to follow: 5559468539
2018-01-10 22:43:15,998 - someusername - Followed: 5559468539 #2.
2018-01-10 22:44:10,939 - someusername - Trying to like media: 1689331762959828944
2018-01-10 22:44:11,546 - someusername - Liked: 1689331762959828944. Like #5.
2018-01-10 22:46:15,047 - someusername - Trying to like media: 1689331749529950612
2018-01-10 22:46:15,640 - someusername - Liked: 1689331749529950612. Like #6.
2018-01-10 22:48:19,304 - someusername - Trying to like media: 1689331687227859600
2018-01-10 22:48:19,918 - someusername - Liked: 1689331687227859600. Like #7.
2018-01-10 22:48:23,527 - someusername - Get media id by tag: filmphotographic
2018-01-10 22:48:25,548 - someusername - Removing already liked medias..
````

**Comment by ugurozturk** [comment]
@iceman183 share example.py and error.log please. It looks so weird.

**Comment by ugurozturk** [comment]
@iceman183 it removes already liked medias to save time. Then the bot wouldn't try to like a media second time

**Comment by iceman183** [comment]
@ugurozturk Ah, alright. That makes sense. I got confused. I thought it was removing likes from already liked medias and I wondered why it was doing that. I get it now. Very smart.

As for the error.log, I restarted the script so the error log got overwritten. I'm waiting to see if the error happens again, so far it doesn't seem to have been repeated. Maybe it was a one-off thing? 

I also read on your readme.md that there is a start and stop hour and minute. Lets If I do use it, will it divide the time for the total number of likes, comments and follows within the start and stop time? 

Also, let me know if you need any help from on anything in terms of coding. I would be happy to dedicate my time to this repo as well. Good job 👍

**Comment by ugurozturk** [comment]
@iceman183 yeah it does divide lil bit, if you want 1000likes /day but setting start and stop time, like working 7am-23pm make it like 1200likes/day or 1300 as your wish. I will keep this issue open for a while if you had this following error again please comment here.

**Comment by iceman183** [comment]
@ugurozturk This issue doesn't seem to have returned. Maybe it was a one-off thing. I'll let it be for now but there does seem to be another issue that is taking place. 

After about 7 hours of the script running I started "Not Liked: 400" error and every now and then (rare though) "Except on get_media!"

1. Except on get_media

````
INFO:someusername:Get media id by tag: 
INFO:someusername:Except on get_media!
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/json/decoder.py", line 368, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/instabot.pyV2/src/instabot.py", line 367, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/local/lib/python3.3/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.3/json/decoder.py", line 352, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.3/json/decoder.py", line 370, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO:someusername:Removing already liked medias..
INFO:someusername:Get media id by tag: streetsofindia
````

This happened a total of 5-6 times in 12 hours. 

````
2018-01-11 07:18:04,062 - someusername - Get media id by tag: 
2018-01-11 07:18:04,532 - someusername - Except on get_media!
2018-01-11 07:18:04,533 - someusername - Removing already liked medias..
2018-01-11 07:18:07,537 - someusername - Get media id by tag: bokeh
2018-01-11 07:18:10,395 - someusername - Removing already liked medias..
2018-01-11 07:18:10,400 - someusername - Trying to follow: 2288805543
2018-01-11 07:18:10,964 - someusername - Followed: 2288805543 #56.
2018-01-11 07:18:12,499 - someusername - Trying to comment: 1689593308491469066
2018-01-11 07:18:13,658 - someusername - Write: "Love your work". #56.
2018-01-11 07:20:17,169 - someusername - Trying to like media: 1689593308491469066
2018-01-11 07:20:18,039 - someusername - Not liked: 400
2018-01-11 09:20:18,146 - someusername - Trying to follow: 4570727442
2018-01-11 09:20:19,587 - someusername - Followed: 4570727442 #57.
2018-01-11 09:20:21,109 - someusername - Trying to comment: 1689593010168574848
2018-01-11 09:20:22,085 - someusername - Write: "Wow!". #57.
2018-01-11 09:22:25,591 - someusername - Trying to like media: 1689593010168574848
2018-01-11 09:22:26,416 - someusername - Not liked: 400
````

The funny thing is that it continues to comment and follow but not able to like and there is this weird time lag between the log where there is no log between 7:20 to 9:20 as if nothing happened in those two hours and errors as such on error.log so it has to be something with connectivity but it if follows and comments, it shouldn't be. and again from 9:22 till now, it hasn't logged anything (one hour later). 

I've attached my errors.log file as well. Don't get confused as it mentions the second log of mine as well which is mentioned through "someusernameu" as opposed to "someusername" because I wanted a second log with just the usernames of the people.

my config file 
````
bot = InstaBot(
	like_per_day=700,
	comments_per_day=200,
	media_max_like=150,
	media_min_like=0,
	follow_per_day=200,
	max_like_for_one_tag=5,
	follow_time=1 * 60,
	unfollow_per_day=3,
	unfollow_break_min=15,
        unfollow_break_max=30,
````
[errors.log](https://github.com/ugurozturk/instabot.pyV2/files/1621299/errors.log)

**Comment by iceman183** [comment]
@ugurozturk Update 
So I created a manual login session on python from my laptop and ran the like, follow and comment from within the session by manually sending post request to urls with data. They all worked. Seems like VPS is blocked for likes only and that too after 200 something likes, weird.

**Comment by iceman183** [comment]
Yup, likes were blocked. I get the following data back on vps - "This post can't be liked right now. Try again in a minute or tell us if you think we made a mistake." Weird. Extremely weird but oh well. The repeated follows issue hasn't come back so that may have been a one-off and the rest doesn't really matter cause it was cause by the block. I'll just change my VPS now and going to close this issue since it seems to be resolved as of now. Thanks @ugurozturk

**Comment by ugurozturk** [comment]
@iceman183 there is something i did read "shadow ban" from original repo issues. They say sometimes instagram does that and you need to let the bot sleep some time like 8hours. Error 400 's solution is not found, and the main reason is also unknown. I was using this repo in my android but i realized it does so low likes in android. I am using it in my local machine now for 1days. 

PS your commenting valume looks high, i dont using the feature so i am not sure but it might be as much as following limit, it is really trackable and dangerous feature

**Comment by iceman183** [comment]
@ugurozturk I know about shadowban but the shadowban has more to do with post being hidden from tags, follower counts dropping etc. This is a very specific IP ban and that too for likes only. Which is weird.

Yeah, I was pushing the commenting and follows per day a bit more than I'm used to but its weird that they didnt ban the commenting or following, just the likes, that too after 200 likes. I've safely reached 500 likes, and 110 comments and follows in earlier runs last month. I did take a 15 days break from running the bot. I'll try again with lower limits and see how it works.
