### ISSUE TITLE
TypeError: must be str, not int

### ISSUE THREAD

**Issue by heydanaye** [ugurozturk/instabot.pyV2#39]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [X] Did read [FAQ](https://github.com/ugurozturk/instabot.pyV2/wiki/FAQ)
- [X] Searched and checked other issues about my problem
- [ ] If have errors.log file and i did upload it

Check One :
- [X] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
MAC 
## Python Version ?
3x
## Is it VPS ?
No
### VPS: Is the vps far far away ? Another Country ?
No
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 6/10

-----------------------------------------------------

Hi I'm having issues with the bot shutting it self off after 200 or so likes. I set it up to only like media (no follows or unfollows). I get this message.

Traceback (most recent call last):
  File "example.py", line 71, in <module>
    bot.new_auto_mod()
  File "/Users/dannyt/Desktop/Python/instabot.pyV2-masterv2/src/instabot.py", line 685, in new_auto_mod
    self.new_auto_mod_like()
  File "/Users/dannyt/Desktop/Python/instabot.pyV2-masterv2/src/instabot.py", line 713, in new_auto_mod_like
    if self.like_all_exist_media(media_size=1, delay=False):
  File "/Users/dannyt/Desktop/Python/instabot.pyV2-masterv2/src/instabot.py", line 534, in like_all_exist_media
    status=like.status_code)
  File "/Users/dannyt/Desktop/Python/instabot.pyV2-masterv2/src/sql_updates.py", line 58, in insert_media
    media_id +"','"+ status +"','"+ str(now) +"')")
TypeError: must be str, not int

Please help! 

Thanks,
Danny

**Comment by ugurozturk** [comment]
I merged in original repo https://github.com/instabot-py/instabot.py
